import { EventFormat, DecaEvent } from "./ValidatorTypes";
const PROJECT_MANAGEMENT_SECTIONS = [
  ["Executive Summary"],
  ["Initiating"],
  ["Planning and Organizing"],
  ["Execution"],
  ["Monitoring and Controlling"],
  ["Closing the Project"],
  ["Bibliography"],
];
const OPERATIONS_RESEARCH_SECTIONS = [
  ["Table of Contents"],
  ["Executive Summary"],
  ["Introduction"],
  ["Research Methods Used in the Study"],
  ["Findings and Conclusions of the Study"],
  ["Proposed Strategic Plan"],
  ["Proposed Budget"],
  ["Bibliography"],
];
const INTEGRATED_MARKETING_CAMPAIGN_SECTIONS = [
  ["Overview"],
  ["Description of Event", "Description of Product" , "Description of Service"],
  ["Campaign Objectives"],
  ["Campaign Target Market"],
  ["Campaign Activities and Schedule"],
  ["Budget"],
  ["Key Metrics"],
  ["Bibliography"],
];
export const DECA_EVENTS_OBJECT: Record<string, DecaEvent> = {
  "Business Services Operations Research Event": {
    name: "Business Services Operations Research Event",
    sections: OPERATIONS_RESEARCH_SECTIONS,
    category: "Business Operations Research",
    type: EventFormat.Written,
  },
  "Buying and Merchandising Operations Research Event": {
    name: "Buying and Merchandising Operations Research Event",
    sections: OPERATIONS_RESEARCH_SECTIONS,
    category: "Business Operations Research",
    type: EventFormat.Written,
  },
  "Finance Operations Research Event": {
    name: "Finance Operations Research Event",
    sections: OPERATIONS_RESEARCH_SECTIONS,
    category: "Business Operations Research",
    type: EventFormat.Written,
  },
  "Hospitality and Tourism Operations Research Event": {
    name: "Hospitality and Tourism Operations Research Event",
    sections: OPERATIONS_RESEARCH_SECTIONS,
    category: "Business Operations Research",
    type: EventFormat.Written,
  },
  "Sports and Entertainment Marketing Operations Research Event": {
    name: "Sports and Entertainment Marketing Operations Research Event",
    sections: OPERATIONS_RESEARCH_SECTIONS,
    category: "Business Operations Research",
    type: EventFormat.Written,
  },
  "Business Solutions Project": {
    name: "Business Solutions Project",
    sections: PROJECT_MANAGEMENT_SECTIONS,
    category: "Project Management",
    type: EventFormat.Written,
  },
  "Career Development Project": {
    name: "Career Development Project",
    sections: PROJECT_MANAGEMENT_SECTIONS,
    category: "Project Management",
    type: EventFormat.Written,
  },
  "Community Awareness Project": {
    name: "Community Awareness Project",
    sections: PROJECT_MANAGEMENT_SECTIONS,
    category: "Project Management",
    type: EventFormat.Written,
  },
  "Community Giving Project": {
    name: "Community Giving Project",
    sections: PROJECT_MANAGEMENT_SECTIONS,
    category: "Project Management",
    type: EventFormat.Written,
  },
  "Financial Literacy Project": {
    name: "Financial Literacy Project",
    sections: PROJECT_MANAGEMENT_SECTIONS,
    category: "Project Management",
    type: EventFormat.Written,
  },
  "Sales Project": {
    name: "Sales Project",
    sections: PROJECT_MANAGEMENT_SECTIONS,
    category: "Project Management",
    type: EventFormat.Written,
  },
  "Innovation Plan": {
    name: "Innovation Plan",
    sections: [
      ["Overview"],
      ["Problem"],
      ["Customer Segments"],
      ["Unique Value Proposition"],
      ["Solution"],
      ["Conclusion"],
      ["Bibliography"],
    ],
    category: "Entrepreneurship",
    type: EventFormat.Pitch,
  },
  "Start-Up Business Plan": {
    name: "Start-Up Business Plan",
    sections: [
      ["Overview"],
      ["Problem"],
      ["Customer Segments"],
      ["Unique Value Proposition"],
      ["Solutions"],
      ["Channels"],
      ["Revenue Streams"],
      ["Cost Structure"],
      ["Key Metrics"],
      ["Competitive Advantage"],
      ["Conclusion"],
      ["Bibliography"],
    ],
    category: "Entrepreneurship",
    type: EventFormat.Pitch,
  },
  "Independent Business Plan": {
    name: "Independent Business Plan",
    sections: [
      ["Executive Summary"],
      ["Problem"],
      ["Customer Segments"],
      ["Unique Value Proposition"],
      ["Solution"],
      ["Channels"],
      ["Revenue Streams"],
      ["Cost Structure"],
      ["Detailed Financials"],
      ["Key Metrics"],
      ["Competitive Advantage"],
      ["Conclusion"],
      ["Bibliography"],
    ],
    category: "Entrepreneurship",
    type: EventFormat.Written,
  },
  "International Business Plan": {
    name: "International Business Plan",
    sections: [
      ["Executive Summary"],
      ["Analysis of the International Business Situation"],
      ["Problem"],
      ["Customer Segments"],
      ["Unique Value Proposition"],
      ["Solution"],
      ["Channels"],
      ["Revenue Streams"],
      ["Cost Structure"],
      ["Detailed Financials"],
      ["Key Metrics"],
      ["Competitive Advantage"],
      ["Conclusion"],
      ["Bibliography"],
    ],
    category: "Entrepreneurship",
    type: EventFormat.Written,
  },
  "Business Growth Plan": {
    name: "Business Growth Plan",
    sections: [
      ["Executive Summary"],
      ["Introduction"],
      ["SWOT Analysis"],
      ["Five Year Plan to Grow and Expand the Business"],
      ["Financing Plan"],
      ["Conclusion"],
      ["Bibliography"],
    ],
    category: "Entrepreneurship",
    type: EventFormat.Written,
  },
  "Franchise Business Plan": {
    name: "Franchise Business Plan",
    sections: [
      ["Executive Summary"],
      ["Business History, Background and Objectives", "Business History, Background & Objectives"],
      ["Business Environment"],
      ["Products and Services", "Products or Services", "Prodcuts and/or Services"],
      ["Present Market"],
      ["Competition"],
      ["Marketing Plan"],
      ["Management and Organization", "Management & Organization"],
      ["Business Resources"],
      ["Financial Plan and Data", "Financial Plan & Data"],
      ["Conclusion"],
      ["Bibliography"],
    ],
    category: "Entrepreneurship",
    type: EventFormat.Written,
  },
  "Integrated Marketing Campaign–Event": {
    name: "Integrated Marketing Campaign–Event",
    sections: INTEGRATED_MARKETING_CAMPAIGN_SECTIONS,
    category: "Integrated Marketing Campaign",
    type: EventFormat.Pitch,
  },
  "Integrated Marketing Campaign–Service": {
    name: "Integrated Marketing Campaign–Service",
    sections: INTEGRATED_MARKETING_CAMPAIGN_SECTIONS,
    category: "Integrated Marketing Campaign",
    type: EventFormat.Pitch,
  },
  "Integrated Marketing Campaign–Product": {
    name: "Integrated Marketing Campaign–Product",
    sections: INTEGRATED_MARKETING_CAMPAIGN_SECTIONS,
    category: "Integrated Marketing Campaign",
    type: EventFormat.Pitch,
  },
  "Stock Market Game": {
    name: "Stock Market Game",
    sections: [
      ["Overview"],
      ["Analysis of Portfolio Performance"],
      ["Rationale"],
      ["Conclusions and Findings"],
      ["Bibliography"],
    ],
    category: "Stock Market Game",
    type: EventFormat.Pitch,
  },
};

