import { EventFormat, DecaEvent } from "./validators/ValidatorTypes";
const PROJECT_MANAGEMENT_SECTIONS = [
  "Executive Summary",
  "Initiating",
  "Planning and Organizing",
  "Execution",
  "Monitoring and Controlling",
  "Closing the Project",
  "Bibliography",
];
const OPERATIONS_RESEARCH_SECTIONS = [
  "Table of Contents",
  "Executive Summary",
  "Introduction",
  "Research Methods Used in the Study",
  "Findings and Conclusions of the Study",
  "Proposed Strategic Plan",
  "Proposed Budget",
  "Bibliography",
];
const INTEGRATED_MARKETING_CAMPAIGN_SECTIONS = [
  "Overview",
  "Description of the Event, Product or Service and Its Company",
  "Campaign Objectives",
  "Campaign Target Market",
  "Campaign Activities and Schedule",
  "Budget",
  "Key Metrics",
  "Bibliography",
];
export const DECA_EVENTS_OBJECT = {
  BSOR: {
    name: "Business Services Operations Research Event",
    sections: OPERATIONS_RESEARCH_SECTIONS,
    type: EventFormat.Written,
  },
  BMOR: {
    name: "Buying and Merchandising Operations Research Event",
    sections: OPERATIONS_RESEARCH_SECTIONS,
    type: EventFormat.Written,
  },
  FOR: {
    name: "Finance Operations Research Event",
    sections: OPERATIONS_RESEARCH_SECTIONS,
    type: EventFormat.Written,
  },
  HTOR: {
    name: "Hospitality and Tourism Operations Research Event",
    sections: OPERATIONS_RESEARCH_SECTIONS,
    type: EventFormat.Written,
  },
  SEMOR: {
    name: "Sports and Entertainment Marketing Operations Research Event",
    sections: OPERATIONS_RESEARCH_SECTIONS,
    type: EventFormat.Written,
  },
  BSP: {
    name: "Business Solutions Project",
    sections: PROJECT_MANAGEMENT_SECTIONS,
    type: EventFormat.Written,
  },
  CDP: {
    name: "Career Development Project",
    sections: PROJECT_MANAGEMENT_SECTIONS,
    type: EventFormat.Written,
  },
  CAP: {
    name: "Community Awareness Project",
    sections: PROJECT_MANAGEMENT_SECTIONS,
    type: EventFormat.Written,
  },
  CGP: {
    name: "Community Giving Project",
    sections: PROJECT_MANAGEMENT_SECTIONS,
    type: EventFormat.Written,
  },
  FLP: {
    name: "Financial Literacy Project",
    sections: PROJECT_MANAGEMENT_SECTIONS,
    type: EventFormat.Written,
  },
  SP: {
    name: "Sales Project",
    sections: PROJECT_MANAGEMENT_SECTIONS,
    type: EventFormat.Written,
  },
  IP: {
    name: "Innovation Plan",
    sections: [
      "Overview",
      "Problem",
      "Customer Segments",
      "Unique Value Proposition",
      "Solution",
      "Conclusion",
      "Bibliography",
    ],
    type: EventFormat.Pitch,
  },
  SUBP: {
    name: "Start-Up Business Plan",
    sections: [
      "Overview",
      "Problem",
      "Customer Segments",
      "Unique Value Proposition",
      "Solutions",
      "Channels",
      "Revenue Streams",
      "Cost Structure",
      "Key Metrics",
      "Competitive Advantage",
      "Conclusion",
      "Bibliography",
    ],
    type: EventFormat.Pitch,
  },
  IBP: {
    name: "Independent Business Plan",
    sections: [
      "Executive Summary",
      "Problem",
      "Customer Segments",
      "Unique Value Proposition",
      "Solution",
      "Channels",
      "Revenue Streams",
      "Cost Structure",
      "Detailed Financials",
      "Key Metrics",
      "Competitive Advantage",
      "Conclusion",
      "Bibliography",
    ],
    type: EventFormat.Written,
  },
  INTBP: {
    name: "International Business Plan",
    sections: [
      "Executive Summary",
      "Analysis of the International Business Situation",
      "Problem",
      "Customer Segments",
      "Unique Value Proposition",
      "Solution",
      "Channels",
      "Revenue Streams",
      "Cost Structure",
      "Detailed Financials",
      "Key Metrics",
      "Competitive Advantage",
      "Conclusion",
      "Bibliography",
    ],
    type: EventFormat.Written,
  },
  BGP: {
    name: "Business Growth Plan",
    sections: [
      "Executive Summary",
      "Introduction",
      "SWOT Analysis",
      "Five Year Plan to Grow and Expand the Business",
      "Financing Plan",
      "Conclusion",
      "Bibliography",
    ],
    type: EventFormat.Written,
  },
  FBP: {
    name: "Franchise Business Plan",
    sections: [
      "Executive Summary",
      "Business History, Background and Objectives",
      "Business Environment",
      "Products and/or Services",
      "Present Market",
      "Competition",
      "Marketing Plan",
      "Management and Organization",
      "Business Resources",
      "Financial Plan and Data",
      "Conclusion",
      "Bibliography",
    ],
    type: EventFormat.Written,
  },
  IMCE: {
    name: "Integrated Marketing Campaign–Event",
    sections: INTEGRATED_MARKETING_CAMPAIGN_SECTIONS,
    type: EventFormat.Pitch,
  },
  IMCS: {
    name: "Integrated Marketing Campaign–Service",
    sections: INTEGRATED_MARKETING_CAMPAIGN_SECTIONS,
    type: EventFormat.Pitch,
  },
  IMCP: {
    name: "Integrated Marketing Campaign–Product",
    sections: INTEGRATED_MARKETING_CAMPAIGN_SECTIONS,
    type: EventFormat.Pitch,
  },
 SMG: {
    name: "Stock Market Game",
    sections: [
      "Overview",
      "Analysis of Portfolio Performance",
      "Rationale",
      "Conclusions and Findings",
      "Bibliography",
    ],
    type: EventFormat.Pitch,
  },
};
export const DECA_EVENTS: DecaEvent[] = [
  {
    name: "Business Services Operations Research Event",
    sections: OPERATIONS_RESEARCH_SECTIONS,
    type: EventFormat.Written,
  },
  {
    name: "Buying and Merchandising Operations Research Event",
    sections: OPERATIONS_RESEARCH_SECTIONS,
    type: EventFormat.Written,
  },
  {
    name: "Finance Operations Research Event",
    sections: OPERATIONS_RESEARCH_SECTIONS,
    type: EventFormat.Written,
  },
  {
    name: "Hospitality and Tourism Operations Research Event",
    sections: OPERATIONS_RESEARCH_SECTIONS,
    type: EventFormat.Written,
  },
  {
    name: "Sports and Entertainment Marketing Operations Research Event",
    sections: OPERATIONS_RESEARCH_SECTIONS,
    type: EventFormat.Written,
  },

  {
    name: "Business Solutions Project",
    sections: PROJECT_MANAGEMENT_SECTIONS,
    type: EventFormat.Written,
  },
  {
    name: "Career Development Project",
    sections: PROJECT_MANAGEMENT_SECTIONS,
    type: EventFormat.Written,
  },
  {
    name: "Community Awareness Project",
    sections: PROJECT_MANAGEMENT_SECTIONS,
    type: EventFormat.Written,
  },
  {
    name: "Community Giving Project",
    sections: PROJECT_MANAGEMENT_SECTIONS,
    type: EventFormat.Written,
  },
  {
    name: "Financial Literacy Project",
    sections: PROJECT_MANAGEMENT_SECTIONS,
    type: EventFormat.Written,
  },
  {
    name: "Sales Project",
    sections: PROJECT_MANAGEMENT_SECTIONS,
    type: EventFormat.Written,
  },

  {
    name: "Innovation Plan",
    sections: [
      "Overview",
      "Problem",
      "Customer Segments",
      "Unique Value Proposition",
      "Solution",
      "Conclusion",
      "Bibliography",
    ],
    type: EventFormat.Pitch,
  },
  {
    name: "Start-Up Business Plan",
    sections: [
      "Overview",
      "Problem",
      "Customer Segments",
      "Unique Value Proposition",
      "Solutions",
      "Channels",
      "Revenue Streams",
      "Cost Structure",
      "Key Metrics",
      "Competitive Advantage",
      "Conclusion",
      "Bibliography",
    ],
    type: EventFormat.Pitch,
  },

  {
    name: "Independent Business Plan",
    sections: [
      "Executive Summary",
      "Problem",
      "Customer Segments",
      "Unique Value Proposition",
      "Solution",
      "Channels",
      "Revenue Streams",
      "Cost Structure",
      "Detailed Financials",
      "Key Metrics",
      "Competitive Advantage",
      "Conclusion",
      "Bibliography",
    ],
    type: EventFormat.Written,
  },
  {
    name: "International Business Plan",
    sections: [
      "Executive Summary",
      "Analysis of the International Business Situation",
      "Problem",
      "Customer Segments",
      "Unique Value Proposition",
      "Solution",
      "Channels",
      "Revenue Streams",
      "Cost Structure",
      "Detailed Financials",
      "Key Metrics",
      "Competitive Advantage",
      "Conclusion",
      "Bibliography",
    ],
    type: EventFormat.Written,
  },
  {
    name: "Business Growth Plan",
    sections: [
      "Executive Summary",
      "Introduction",
      "SWOT Analysis",
      "Five Year Plan to Grow and Expand the Business",
      "Financing Plan",
      "Conclusion",
      "Bibliography",
    ],
    type: EventFormat.Written,
  },
  {
    name: "Franchise Business Plan",
    sections: [
      "Executive Summary",
      "Business History, Background and Objectives",
      "Business Environment",
      "Products and/or Services",
      "Present Market",
      "Competition",
      "Marketing Plan",
      "Management and Organization",
      "Business Resources",
      "Financial Plan and Data",
      "Conclusion",
      "Bibliography",
    ],
    type: EventFormat.Written,
  },

  {
    name: "Integrated Marketing Campaign–Event",
    sections: INTEGRATED_MARKETING_CAMPAIGN_SECTIONS,
    type: EventFormat.Pitch,
  },
  {
    name: "Integrated Marketing Campaign–Service",
    sections: INTEGRATED_MARKETING_CAMPAIGN_SECTIONS,
    type: EventFormat.Pitch,
  },
  {
    name: "Integrated Marketing Campaign–Product",
    sections: INTEGRATED_MARKETING_CAMPAIGN_SECTIONS,
    type: EventFormat.Pitch,
  },

  {
    name: "Stock Market Game",
    sections: [
      "Overview",
      "Analysis of Portfolio Performance",
      "Rationale",
      "Conclusions and Findings",
      "Bibliography",
    ],
    type: EventFormat.Pitch,
  },
];
